# -*- coding: utf-8 -*-
"""AttendancePythonProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12P9gUNYYP_-EWxXLWAaH9KMsR0aLQwRx
"""

students_data = []

def add_student():
    student_id = input("Enter Student ID : ")
    student_name = input("Enter Student Name : ")
    student_course = input("Enter the course chosen ") #the student course has been inputted 
    classes_attended = int(input("Enter Classes Attended : "))
    total_classes = int(input("Enter Total Classes : "))

    new_student = {
        "Student ID": student_id,
        "Student Name": student_name,
        "Student Course" : student_course, #student course has been updated in the dictionary
        "Total classes": total_classes,
        "Classes Attended": classes_attended
    }
    students_data.append(new_student)
    print(f"Student {student_name} (ID: {student_id}) added successfully.")

def classes_details():
    if not students_data:
        print("No student data available.")
        return

    print("\n-- Attendance Details and Exam Allowance --")
    for student in students_data:
        student_name = student["Student Name"]
        classes_attended = student["Classes Attended"]
        total_classes = student["Total classes"]
        if total_classes == 0:
            attendance_percentage = 0.0
            print(f"Error: Total classes for {student_name} is 0. Cannot calculate attendance.")
        else:
            attendance_percentage = (classes_attended / total_classes) * 100
        print(f"Student: {student_name}, Attendance: {attendance_percentage:.2f}%")
        exam_allowance(attendance_percentage, student_name)

def exam_allowance(attendance_percentage, student_name):
  if attendance_percentage >= 75:
    print(f"{student_name} has access to write the exam")
  else :
    print(f"{student_name} does not have access to write the exam due to low attendance.")

def main():
    while True:
        print("\n--- Student Attendance System Menu ---")
        print("1. Add New Student")
        print("2. View Attendance Details and Exam Allowance")
        print("3. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            add_student()
        elif choice == '2':
            classes_details()
        elif choice == '3':
            print("Exiting attendance program.")
            break
        else:
            print("Invalid choice. Please try again.")


if __name__ == "__main__":

    main()
